### PR TITLE
fix: Bump very_good_analysis & prepare for latest flutter version

### PR DESCRIPTION
**Pull request by pedromassango**
## Description

Migrate deprecated members & bump `very_good_analysis`

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by btrautmann** [comment]
@pedromassango probably the highest version we could adopt while keeping dart/Flutter constraints the same (which is desirable) is `5.1.0` based on the [changelog](https://pub.dev/packages/very_good_analysis/changelog).

**Comment by pedromassango** [comment]
> @pedromassango probably the highest version we could adopt while keeping dart/Flutter constraints the same (which is desirable) is `5.1.0` based on the [changelog](https://pub.dev/packages/very_good_analysis/changelog).

It that case, how to we use the package while using the most common lint rules?

I get this in a private project, and can't ignore it across all files or disable this lint

Screenshot 2024-09-24 at 22 43 33

**Comment by btrautmann** [comment]
> It that case, how to we use the package while using the most common lint rules?

That lint is unrelated to `alchemist`, no? It's just stating that you're calling `goldenTest` (an `async` function in a non-`async` function (`main`). You can add the `async` modifier to `main` if you want and `await` `goldenTest` if you want this lint to be satisfied.

**Comment by pedromassango** [comment]
will close this for now

**Comment by jeroen-meijer** [comment]
Quick tip that you probably don't want to await a `goldenTest` call, right?

**Comment by pedromassango** [comment]
> Quick tip that you probably don't want to await a `goldenTest` call, right?

Yes

**Pull request closed without merging**
