### PR TITLE
fix!: use textScaler instead of a double

### PR DESCRIPTION
**Pull request by vanlooverenkoen**
## Description

Give people more control over the textScaleFactor with an actual textScaler instead of the textScaleFactor double

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [X] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [X] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by jeroen-meijer — APPROVED** [review]
LGTM

@btrautmann I'll leave final review up to you, but I think there's no harm in supporting this.
It is technically a (partially) breaking change though, so not sure what to do versioning-wise.

**Review by btrautmann — APPROVED** [review]
domain lgtm
platform lgtm

**Comment by btrautmann** [comment]
> LGTM
> 
> @btrautmann I'll leave final review up to you, but I think there's no harm in supporting this. It is technically a (partially) breaking change though, so not sure what to do versioning-wise.

Yeah, I'll version it accordingly (minor bump since we're still pre-1.0.0)

**Comment by btrautmann** [comment]
Thanks @vanlooverenkoen!

**Pull request merged**
