### PR TITLE
fix: loading fonts from other packages

### PR DESCRIPTION
**Pull request by krispypen**
## Description

Font rendering did not work when fonts are from another package. We are using a separate package for our styleguide including assets, textstyles and fonts... This change makes it possible.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by TimmyChannel** [comment]
Thank you!

**Comment by btrautmann** [comment]
@krispypen mind pushing an empty commit to your branch? We updated CI configuration on our end which seems to have reset the statuses for `build` and `pana` and AFAIK Github UI has no way of kicking these off separately/manually. I'll re-approve upon success and we can get this merged.

**Comment by krispypen** [comment]
hey @btrautmann I pushed an empty commit, not sure if it's actually triggering something now

**Comment by pedromassango** [comment]
Hi everyone, can we get this in, pls?

**Comment by btrautmann** [comment]
> Hi everyone, can we get this in, pls?

@krispypen just needs to patch/address the one failing test

**Comment by krispypen** [comment]
oh, having a look sorry 🥹

**Comment by krispypen** [comment]
I did the change and locally it works, but it looks like someone needs to approve before the test runs.

**Review by btrautmann — APPROVED** [review]
domain lgtm
platform lgtm

**Pull request merged**
